const { useState, useEffect, useRef, useMemo, useReducer, createContext, useContext } = React;
const Ctx=createContext();
const LANGS={fr:"Français",en:"English",es:"Español"};

/* ========== DATA ========== */
const CATS=[{id:"all",label:"Tout",icon:"✨"},{id:"tools",label:"Bricolage",icon:"🔧"},{id:"electronics",label:"Électronique",icon:"📷"},{id:"vehicles",label:"Véhicules",icon:"🚗"},{id:"sports",label:"Sport",icon:"🏄"},{id:"garden",label:"Jardin",icon:"🌿"},{id:"events",label:"Événementiel",icon:"🎉"},{id:"music",label:"Musique",icon:"🎸"},{id:"gaming",label:"Gaming",icon:"🎮"},{id:"baby",label:"Bébé",icon:"👶"},{id:"fashion",label:"Mode",icon:"👗"},{id:"camping",label:"Camping",icon:"⛺"},{id:"kitchen",label:"Cuisine",icon:"🍳"},{id:"photo",label:"Photo",icon:"🎬"},{id:"diy",label:"Créatif",icon:"🎨"},{id:"furniture",label:"Mobilier",icon:"🛋️"}];
const CC={tools:["#F59E0B","#D97706"],electronics:["#3B82F6","#2563EB"],vehicles:["#10B981","#059669"],sports:["#06B6D4","#0891B2"],garden:["#22C55E","#16A34A"],events:["#F43F5E","#E11D48"],music:["#8B5CF6","#7C3AED"],gaming:["#EC4899","#DB2777"],baby:["#F9A8D4","#F472B6"],fashion:["#A78BFA","#8B5CF6"],camping:["#84CC16","#65A30D"],kitchen:["#FB923C","#F97316"],photo:["#64748B","#475569"],diy:["#F472B6","#E879F9"]};
const CE={tools:"🔧",electronics:"📱",vehicles:"🚲",sports:"🏄",garden:"🌱",events:"🎉",music:"🎸",gaming:"🎮",baby:"🧸",fashion:"👗",camping:"⛺",kitchen:"🍳",photo:"📷",diy:"🎨"};
const CATS_FR={tools:'Bricolage',electronics:'Électronique',vehicles:'Véhicules',sports:'Sport',garden:'Jardin',events:'Événementiel',music:'Musique',gaming:'Gaming',baby:'Bébé',fashion:'Mode',camping:'Camping',kitchen:'Cuisine',photo:'Photo',diy:'Créatif',furniture:'Mobilier'};
function rrect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.arcTo(x+w,y,x+w,y+r,r);ctx.lineTo(x+w,y+h-r);ctx.arcTo(x+w,y+h,x+w-r,y+h,r);ctx.lineTo(x+r,y+h);ctx.arcTo(x,y+h,x,y+h-r,r);ctx.lineTo(x,y+r);ctx.arcTo(x,y,x+r,y,r);ctx.closePath()}
function mkImg(cat,id,v=0){const cnv=document.createElement('canvas');cnv.width=400;cnv.height=300;const ctx=cnv.getContext('2d');const e=CE[cat]||'📦';const pals=[['#6C63FF','#A78BFA'],['#7C3AED','#8B5CF6'],['#8B5CF6','#C4B5FD']];const[c1,c2]=pals[v%pals.length];const gr=ctx.createLinearGradient(0,0,400,300);gr.addColorStop(0,c1);gr.addColorStop(1,c2);ctx.fillStyle=gr;ctx.fillRect(0,0,400,300);ctx.fillStyle='rgba(255,255,255,0.07)';for(let x=20;x<400;x+=40)for(let y=20;y<300;y+=40){ctx.beginPath();ctx.arc(x,y,2.5,0,Math.PI*2);ctx.fill();}ctx.fillStyle='rgba(255,255,255,0.22)';ctx.beginPath();ctx.arc(200,126,58,0,Math.PI*2);ctx.fill();ctx.font='58px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(e,200,126);const lbl=CATS_FR[cat]||cat;ctx.font='600 12px system-ui,-apple-system,sans-serif';const tw=ctx.measureText(lbl).width;ctx.fillStyle='rgba(255,255,255,0.25)';rrect(ctx,200-tw/2-14,213,tw+28,26,13);ctx.fill();ctx.fillStyle='rgba(255,255,255,0.95)';ctx.fillText(lbl,200,226);return cnv.toDataURL();}
const LOCS=["Paris 11e","Lyon 3e","Marseille 6e","Bordeaux","Nantes","Toulouse","Lille","Strasbourg","Montpellier","Nice","Rennes","Grenoble"];
const LL={"Paris 11e":[48.859,2.381],"Lyon 3e":[45.753,4.851],"Marseille 6e":[43.289,5.381],Bordeaux:[44.837,-.579],Nantes:[47.218,-1.553],Toulouse:[43.604,1.444],Lille:[50.629,3.057],Strasbourg:[48.573,7.752],Montpellier:[43.61,3.876],Nice:[43.71,7.262],Rennes:[48.117,-1.677],Grenoble:[45.188,5.724]};
const DESCS=["En excellent état, entretenu régulièrement. Idéal pour vos projets du week-end.","Peu utilisé, comme neuf. Livré avec tous les accessoires.","Matériel professionnel en parfait état. Nettoyé après chaque location.","Utilisé quelques fois. Mode d'emploi et accessoires inclus.","Investissement récent rentabilisé en location. Assurance incluse.","Fiable et testé avant chaque location. Je réponds rapidement !"];
const RAW=[{t:"Perceuse visseuse Bosch Pro",c:"tools",p:12},{t:"Ponceuse orbitale Makita",c:"tools",p:15},{t:"Échelle télescopique 5m",c:"tools",p:8},{t:"Nettoyeur haute pression Kärcher",c:"tools",p:20},{t:"Drone DJI Mini 3 Pro",c:"electronics",p:35},{t:"Console PS5 + 2 manettes",c:"electronics",p:18},{t:"Vidéoprojecteur 4K portable",c:"electronics",p:25},{t:"Enceinte JBL PartyBox 310",c:"electronics",p:22},{t:"Camionnette Renault Master",c:"vehicles",p:55},{t:"Vélo électrique Moustache",c:"vehicles",p:18},{t:"Trottinette électrique Xiaomi",c:"vehicles",p:10},{t:"Remorque porte-vélos",c:"vehicles",p:25},{t:"Paddle gonflable + pagaie",c:"sports",p:20},{t:"Ski Rossignol + chaussures 42",c:"sports",p:22},{t:"VTT Decathlon Rockrider",c:"sports",p:14},{t:"Kayak biplace gonflable",c:"sports",p:28},{t:"Tondeuse robot Husqvarna",c:"garden",p:16},{t:"Taille-haie Stihl",c:"garden",p:14},{t:"Motoculteur 5CV",c:"garden",p:30},{t:"Machine à barbe à papa",c:"events",p:25},{t:"Lot 50 chaises pliantes",c:"events",p:40},{t:"Tonnelle 3x6m + LED",c:"events",p:35},{t:"Guitare acoustique Martin",c:"music",p:15},{t:"Platines DJ Pioneer",c:"music",p:30},{t:"Piano numérique Yamaha",c:"music",p:20},{t:"Casque VR Meta Quest 3",c:"gaming",p:22},{t:"Volant Logitech G29",c:"gaming",p:18},{t:"Poussette Yoyo Babyzen",c:"baby",p:12},{t:"Siège auto Cybex",c:"baby",p:8},{t:"Tente 4 places Quechua",c:"camping",p:15},{t:"Glacière électrique 40L",c:"camping",p:10},{t:"Robot pâtissier KitchenAid",c:"kitchen",p:18},{t:"Raclette & fondue 8 pers.",c:"kitchen",p:10},{t:"Canon EOS R6 + 24-70mm",c:"photo",p:45},{t:"Stabilisateur DJI RS3",c:"photo",p:25},{t:"Robe Sézane T.38",c:"fashion",p:15},{t:"Costume Hugo Boss M",c:"fashion",p:20},{t:"Machine à coudre Singer",c:"diy",p:12},{t:"Imprimante 3D Creality",c:"diy",p:18},{t:"Caméra GoPro Hero 11",c:"electronics",p:28},{t:"Trépied professionnel Manfrotto",c:"photo",p:18},{t:"Téléobjectif Canon 70-200mm",c:"photo",p:35},{t:"VTT électrique Specialized",c:"vehicles",p:32},{t:"Hamac et système de suspension",c:"camping",p:12},{t:"Barbecue gaz Weber Genesis",c:"garden",p:38},{t:"Étagères industrielles en métal",c:"furniture",p:45},{t:"Table basse vintage design",c:"furniture",p:28}];
const USERS=[{id:"u1",name:"Léa Martin",email:"lea@email.com",password:"demo123",avatar:"👩‍🦰",verified:true,since:2022,bio:"Passionnée de partage !",location:"Paris 11e",rating:4.9,rentals:87,responseTime:"~15 min"},{id:"u2",name:"Maxime Dupont",email:"max@email.com",password:"demo123",avatar:"👨‍🦱",verified:true,since:2021,bio:"Je loue ce que je n'utilise pas.",location:"Lyon 3e",rating:4.95,rentals:142,responseTime:"~30 min"},{id:"u3",name:"Chloé Bernard",email:"chloe@email.com",password:"demo123",avatar:"👩",verified:true,since:2023,bio:"Maman de 2 enfants.",location:"Bordeaux",rating:4.8,rentals:34,responseTime:"~1h"},{id:"u4",name:"Antoine Moreau",email:"antoine@email.com",password:"demo123",avatar:"👨",verified:false,since:2024,bio:"Nouveau sur Cercle !",location:"Nantes",rating:4.7,rentals:12,responseTime:"~2h"},{id:"u5",name:"Sarah Petit",email:"sarah@email.com",password:"demo123",avatar:"👩‍🦱",verified:true,since:2020,bio:"Membre fidèle.",location:"Marseille 6e",rating:4.98,rentals:256,responseTime:"~10 min"},{id:"u6",name:"Hugo Lambert",email:"hugo@email.com",password:"demo123",avatar:"👨‍🦳",verified:true,since:2021,bio:"J'adore rendre service.",location:"Toulouse",rating:4.85,rentals:98,responseTime:"~45 min"}];
const buildItems=()=>RAW.map((r,i)=>({id:i+1,title:r.t,cat:r.c,price:r.p,images:[mkImg(r.c,i+1,0),mkImg(r.c,i+1,1),mkImg(r.c,i+1,2)],location:LOCS[i%LOCS.length],rating:+(4.4+Math.random()*.59).toFixed(2),reviews:Math.floor(5+Math.random()*95),owner:USERS[i%USERS.length],description:DESCS[i%DESCS.length],deposit:Math.floor(r.p*3+Math.random()*100),condition:["Comme neuf","Très bon état","Bon état"][i%3],createdAt:"2025",available:true,lat:(LL[LOCS[i%LOCS.length]]||[48.86,2.35])[0]+(.01*Math.random()-.005),lng:(LL[LOCS[i%LOCS.length]]||[48.86,2.35])[1]+(.01*Math.random()-.005)}));
const uid=()=>"_"+Math.random().toString(36).slice(2,8);
const ds=d=>new Date(d).toLocaleDateString("fr-FR",{day:"numeric",month:"short"});

const PRO_USERS=[{id:"p1",name:"Loxam Express",email:"contact@loxam.fr",password:"demo123",avatar:"🏗️",verified:true,since:2019,bio:"N°1 de la location de matériel en France.",location:"Paris 11e",rating:4.92,rentals:1240,responseTime:"~5 min",isPro:true,company:"Loxam"},{id:"p2",name:"Kiloutou",email:"pro@kiloutou.fr",password:"demo123",avatar:"🔶",verified:true,since:2020,bio:"Location de matériel BTP et événementiel.",location:"Lyon 3e",rating:4.88,rentals:890,responseTime:"~10 min",isPro:true,company:"Kiloutou"},{id:"p3",name:"Cyclez Pro",email:"pro@cyclez.fr",password:"demo123",avatar:"🚴",verified:true,since:2022,bio:"Flottes de vélos et trottinettes pour entreprises.",location:"Bordeaux",rating:4.95,rentals:456,responseTime:"~15 min",isPro:true,company:"Cyclez"},{id:"p4",name:"EventPro Location",email:"pro@eventpro.fr",password:"demo123",avatar:"🎪",verified:true,since:2021,bio:"Matériel événementiel haut de gamme.",location:"Marseille 6e",rating:4.90,rentals:678,responseTime:"~8 min",isPro:true,company:"EventPro"}];
const PRO_RAW=[{t:"Nacelle élévatrice 12m",c:"tools",p:120},{t:"Mini-pelle 1.5T",c:"tools",p:180},{t:"Groupe électrogène 5kVA",c:"tools",p:45},{t:"Échafaudage complet 10m",c:"tools",p:65},{t:"Compacteur de sol",c:"tools",p:85},{t:"Bétonnière 350L",c:"tools",p:40},{t:"Flotte 10 vélos élec.",c:"vehicles",p:150},{t:"Flotte 20 trottinettes",c:"vehicles",p:200},{t:"Camion benne 3.5T",c:"vehicles",p:95},{t:"Utilitaire frigorifique",c:"vehicles",p:110},{t:"Sono complète 2000W",c:"events",p:80},{t:"Structure alu 6x4m",c:"events",p:150},{t:"Pack éclairage LED pro",c:"events",p:60},{t:"Barnum 6x12m",c:"events",p:120},{t:"Canon R5 + optiques",c:"photo",p:95},{t:"Kit tournage complet",c:"photo",p:180}];
const buildProItems=()=>PRO_RAW.map((r,i)=>({id:1000+i,title:r.t,cat:r.c,price:r.p,images:[mkImg(r.c,1000+i,0),mkImg(r.c,1000+i,1),mkImg(r.c,1000+i,2)],location:LOCS[(i+3)%LOCS.length],rating:+(4.7+Math.random()*.29).toFixed(2),reviews:Math.floor(20+Math.random()*200),owner:PRO_USERS[i%PRO_USERS.length],description:"Matériel professionnel certifié. Maintenance régulière. Livraison possible sur chantier/site.",deposit:Math.floor(r.p*5+Math.random()*200),condition:"Comme neuf",createdAt:"2025",available:true,isPro:true,lat:(LL[LOCS[(i+3)%LOCS.length]]||[48.86,2.35])[0]+(.01*Math.random()-.005),lng:(LL[LOCS[(i+3)%LOCS.length]]||[48.86,2.35])[1]+(.01*Math.random()-.005)}));

/* ========== REDUCER ========== */
// Helpers de persistence localStorage
const _ls=(key,def)=>{try{const d=localStorage.getItem(key);return d?JSON.parse(d):def;}catch(e){return def;}};
const _savedItems    = _ls('cercle_items',[]);
const _savedBookings = _ls('cercle_bookings',[]);
const _savedPayments = _ls('cercle_payments',[]);
const _savedReviews  = _ls('cercle_reviews',[]);
const _savedBadges   = _ls('cercle_badges',[]);
const _savedWallet   = _ls('cercle_wallet',0);
const _savedFavs     = (()=>{try{const d=localStorage.getItem('cercle_favs');return d?new Set(JSON.parse(d)):new Set();}catch(e){return new Set();}})();
const _savedFollowing=_ls('cercle_following',[]);
const init={user:null,items:buildItems(),proItems:buildProItems(),favorites:_savedFavs,bookings:_savedBookings,messages:[],conversations:[],reviews:_savedReviews,notifications:[],userItems:_savedItems,cloudItems:[],payments:_savedPayments,referrals:[],disputes:[],wallet:_savedWallet,badges:_savedBadges,following:_savedFollowing,profileCompletion:{identity:false,phone:false,drivingLicense:false,bankAccount:false}};
function reducer(s,a){switch(a.type){
  case"LOGIN":{const u={...a.payload,refCode:a.payload.refCode||uid().toUpperCase().slice(0,6)};const fixedItems=s.userItems.map(i=>(!i.owner?.id||i.owner?.email===u.email)?{...i,owner:{...(i.owner||{}),id:u.id,email:u.email}}:i);try{localStorage.setItem('cercle_items',JSON.stringify(fixedItems));}catch(e){}return{...s,user:u,userItems:fixedItems};}
  case"LOGOUT":return{...s,user:null};
  case"UPD_PROF":return{...s,user:{...s.user,...a.payload}};
  case"SET_AVATAR":return{...s,user:{...s.user,avatar:a.avatar,avatarUrl:a.url||null}};
  case"TOG_FAV":{const f=new Set(s.favorites);const isAdding=!f.has(a.id);isAdding?f.add(a.id):f.delete(a.id);if(window.db){const delta=isAdding?1:-1;const inc=window.firebase&&window.firebase.firestore?window.firebase.firestore.FieldValue.increment(delta):null;if(inc)window.db.collection('items').doc(a.id).update({likeCount:inc}).catch(()=>{});}if(isAdding&&window.db&&s.user&&a.ownerId&&a.ownerId!==s.user.id){const notif={userId:a.ownerId,text:`❤️ ${s.user.name||'Quelqu\'un'} a aimé votre annonce "${a.title||''}"`,kind:'like',read:false,at:new Date().toISOString(),itemId:a.id};window.db.collection('notifications').add(notif).catch(()=>{});}return{...s,favorites:f}}
  case"BOOK":{
    const b=a.payload;
    const n={id:uid(),text:`Réservation : ${b.itemTitle}`,read:false,at:new Date()};
    const pay={id:uid(),bookingId:b.id,type:"payment",amount:b.total,status:"completed",method:b.payMethod||"card",date:new Date(),label:`Location : ${b.itemTitle}`};
    const dep={id:uid(),bookingId:b.id,type:"deposit",amount:b.deposit,status:"held",method:b.payMethod||"card",date:new Date(),label:`Caution : ${b.itemTitle}`,itemTitle:b.itemTitle,ownerId:b.ownerId,ownerName:b.ownerName,renterId:b.userId,renterName:s.user?.name||"Locataire"};
    return{...s,bookings:[...s.bookings,b],notifications:[n,...s.notifications],payments:[...s.payments,pay,dep]}}
  case"CANCEL_BOOK":return{...s,bookings:s.bookings.map(b=>b.id===a.id?{...b,status:"cancelled"}:b)};
  case"RELEASE_DEP":{
    const dep=s.payments.find(p=>p.id===a.id);
    const n=dep?{id:uid(),text:`Caution de ${dep.amount}€ restituée (${dep.itemTitle})`,read:false,at:new Date()}:null;
    return{...s,payments:s.payments.map(p=>p.id===a.id?{...p,status:"released",releasedAt:new Date()}:p),notifications:n?[n,...s.notifications]:s.notifications}}
  case"MSG":{const m=a.payload;
    if(s.messages.find(x=>x.id===m.id))return s;
    let cs=[...s.conversations],cv=cs.find(c=>c.id===m.cid);
    const otherName=m.from===s.user?.id?(m.toName||''):( m.fromName||'Utilisateur');
    const otherAvatar=m.from===s.user?.id?(m.toAvatar||'😊'):(m.fromAvatar||'😊');
    if(!cv){cv={id:m.cid,parts:[m.from,m.to],itemId:m.itemId,itemTitle:m.itemTitle||'',last:m.text,at:new Date().toISOString(),otherName,otherAvatar};cs.push(cv)}
    else cs=cs.map(c=>c.id===m.cid?{...c,last:m.text,at:new Date().toISOString()}:c);
    if(window.db&&!m._fromCloud){const msgDoc={...m,_fromCloud:false,sentAt:new Date().toISOString(),timestamp:new Date().toISOString()};window.db.collection('messages').add(msgDoc).catch(e=>console.error('[MSG]',e));}
    if(window.db&&!m._fromCloud&&m.to){const notif={userId:m.to,text:`💬 Nouveau message de ${m.fromName||'quelqu\'un'} sur "${m.itemTitle||'une annonce'}"`,kind:'message',read:false,at:new Date().toISOString(),itemId:m.itemId};window.db.collection('notifications').add(notif).catch(()=>{});}
    return{...s,messages:[...s.messages,m],conversations:cs}}
  case"PUSH_NOTIF":{const n=a.payload;if(s.notifications.find(x=>x.id===n.id))return s;return{...s,notifications:[{...n,read:false},...s.notifications]};}
  case"READ_N":return{...s,notifications:s.notifications.map(n=>({...n,read:true}))};
  case"REVIEW":{const r=a.payload;const items=s.items.map(i=>i.id===r.itemId?{...i,reviews:i.reviews+1,rating:+((i.rating*i.reviews+r.rating)/(i.reviews+1)).toFixed(2)}:i);return{...s,reviews:[...s.reviews,r],items}}
  case"ADD_ITEM":{const owner={...s.user,id:window.firebase&&window.firebase.auth&&window.firebase.auth().currentUser?window.firebase.auth().currentUser.uid:s.user.id};const it={...a.payload,id:uid(),owner,rating:0,reviews:0,createdAt:new Date().toISOString(),isPro:a.payload.isPro||false};const newUserItems=[...s.userItems,it];try{localStorage.setItem('cercle_items',JSON.stringify(newUserItems));}catch(e){console.error('[Cercle] localStorage plein, annonce sauvegardée en mémoire seulement:',e.name);try{const light=newUserItems.map(i=>({...i,images:i.images?.map(im=>im.slice(0,200)+'...'),photos:[]}));localStorage.setItem('cercle_items',JSON.stringify(light));}catch(e2){}}if(window.db){const firestoreItem={...it,images:[],photos:[]};window.db.collection('items').doc(it.id).set(firestoreItem).catch(console.error);}return{...s,userItems:newUserItems,notifications:[{id:uid(),text:`"${it.title}" publiée ! ✅`,read:false,at:new Date()},...s.notifications]}}
  case"READ_ONE":return{...s,notifications:s.notifications.map(n=>n.id===a.id?{...n,read:true}:n)};
  case"REFERRAL":{const n={id:uid(),text:`${a.name} a rejoint Cercle ! +5€`,read:false,at:new Date(),kind:"referral"};return{...s,referrals:[...s.referrals,{id:uid(),name:a.name,date:new Date(),bonus:5}],notifications:[n,...s.notifications]}}
  case"DISPUTE":return{...s,disputes:[...s.disputes,a.payload],notifications:[{id:uid(),text:"Litige ouvert",read:false,at:new Date(),kind:"dispute"},...s.notifications]};
  case"RESOLVE_DISPUTE":return{...s,disputes:s.disputes.map(d=>d.id===a.id?{...d,status:"resolved"}:d)};
  case"VERIFY_ID":return{...s,user:{...s.user,verified:true},notifications:[{id:uid(),text:"Identité vérifiée ✓",read:false,at:new Date(),kind:"system"},...s.notifications]};
  case"ADD_WALLET":return{...s,wallet:s.wallet+(a.amount||0),notifications:[{id:uid(),text:`+${a.amount}€ ajoutés au wallet`,read:false,at:new Date(),kind:"wallet"},...s.notifications]};
  case"PAY_WALLET":return{...s,wallet:Math.max(0,s.wallet-(a.amount||0))};
  case"EARN_BADGE":{if(s.badges.includes(a.badge))return s;const bd=ALL_BADGES.find(b=>b.id===a.badge);const bName=bd?bd.name:a.badge;const bIcon=bd?bd.icon:"🏅";return{...s,badges:[...s.badges,a.badge],notifications:[{id:uid(),text:`🎉 Félicitations ! Badge ${bIcon} "${bName}" débloqué ! Continuez comme ça !`,read:false,at:new Date(),kind:"badge"},...s.notifications]}};
  case"TOGGLE_AVAIL":{const toggle=i=>i.id===a.id?{...i,available:!i.available}:i;return{...s,items:s.items.map(toggle),userItems:s.userItems.map(toggle)}};
  case"SET_PROFILE_COMPLETION":{const pc={...s.profileCompletion,...a.payload};const n={id:uid(),text:`Profil complété : ${a.label||"étape"}`,read:false,at:new Date(),kind:"system"};return{...s,profileCompletion:pc,notifications:[n,...s.notifications]}};
  case"SET_CLOUD_ITEMS":return{...s,cloudItems:a.payload};
  case"FOLLOW":{const f={id:a.userId,name:a.userName,avatar:a.userAvatar,since:a.userSince,followedAt:new Date().toISOString()};const next=[...s.following.filter(u=>u.id!==a.userId),f];try{localStorage.setItem('cercle_following',JSON.stringify(next));}catch(e){}if(window.db&&s.user){const sendFollowNotif=(targetUid)=>{window.db.collection('follows').doc(`${s.user.id}_${targetUid}`).set({followerId:s.user.id,followerName:s.user.name,followerEmail:s.user.email||'',followedId:targetUid,followedEmail:a.ownerEmail||'',followedName:a.userName,at:new Date().toISOString()}).catch(()=>{});window.db.collection('notifications').add({userId:targetUid,text:`👤 ${s.user.name||'Quelqu\'un'} vous suit maintenant`,kind:'follow',read:false,at:new Date().toISOString(),fromId:s.user.id}).catch(()=>{});};if(a.ownerEmail){window.db.collection('users').where('email','==',a.ownerEmail).limit(1).get().then(snap=>{const uid=snap.docs.length>0?snap.docs[0].id:a.userId;sendFollowNotif(uid);}).catch(()=>sendFollowNotif(a.userId));}else{sendFollowNotif(a.userId);}}return{...s,following:next};}
  case"UNFOLLOW":{const next=s.following.filter(u=>u.id!==a.userId);try{localStorage.setItem('cercle_following',JSON.stringify(next));}catch(e){}if(window.db&&s.user){window.db.collection('follows').doc(`${s.user.id}_${a.userId}`).delete().catch(()=>{})}return{...s,following:next};}
  case"EDIT_ITEM":{const upd={...a.payload};const existing=s.userItems.find(i=>i.id===upd.id)||s.items.find(i=>i.id===upd.id)||{};const fullItem={...existing,...upd};const newUserItems=s.userItems.map(i=>i.id===upd.id?fullItem:i);try{localStorage.setItem('cercle_items',JSON.stringify(newUserItems));}catch(e){}if(window.db){const{images,photos,...firestoreItem}=fullItem;window.db.collection('items').doc(upd.id).set(firestoreItem).catch(console.error);}return{...s,userItems:newUserItems,items:s.items.map(i=>i.id===upd.id?fullItem:i)}}
  case"DELETE_ITEM":{const next=s.userItems.filter(i=>i.id!==a.id);try{localStorage.setItem('cercle_items',JSON.stringify(next));}catch(e){}if(window.db){window.db.collection('items').doc(a.id).delete().catch(()=>{})}return{...s,userItems:next,items:s.items.filter(i=>i.id!==a.id)}}
  case"SET_BLOCKED_DATES":{const newUserItems=s.userItems.map(i=>i.id===a.id?{...i,blockedDates:a.dates}:i);try{localStorage.setItem('cercle_items',JSON.stringify(newUserItems));}catch(e){}if(window.db){window.db.collection('items').doc(a.id).update({blockedDates:a.dates}).catch(()=>{})}return{...s,userItems:newUserItems}}
  default:return s}}

/* ========== ICONS ========== */
